/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LbmAmbulanceWlList {
    }
}
declare global {
    interface HTMLLbmAmbulanceWlListElement extends Components.LbmAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLLbmAmbulanceWlListElement: {
        prototype: HTMLLbmAmbulanceWlListElement;
        new (): HTMLLbmAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "lbm-ambulance-wl-list": HTMLLbmAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface LbmAmbulanceWlList {
    }
    interface IntrinsicElements {
        "lbm-ambulance-wl-list": LbmAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lbm-ambulance-wl-list": LocalJSX.LbmAmbulanceWlList & JSXBase.HTMLAttributes<HTMLLbmAmbulanceWlListElement>;
        }
    }
}
